/**
 * GEMINI AI SERVICE
 *
 * This service handles communication with Google's Gemini API
 * to generate score explanations - LLM explanation of score variance and trends
 */

/**
 * Core function to call Gemini API through backend proxy
 * @private
 */
async function callGeminiAPI(prompt, type = 'team-insights') {
  // In production (Vercel), VITE_BACKEND_URL should be empty to use relative URLs
  // In development, it should be 'http://localhost:3002'
  const backendUrl = import.meta.env.VITE_BACKEND_URL !== undefined
    ? import.meta.env.VITE_BACKEND_URL
    : (import.meta.env.DEV ? 'http://localhost:3002' : '');

  console.log('Calling Gemini API:', { type, promptLength: prompt.length });

  const response = await fetch(`${backendUrl}/api/analyze`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ prompt, type }),
  });

  if (!response.ok) {
    const errorData = await response.json().catch(() => ({}));
    console.error('Backend API error:', {
      status: response.status,
      statusText: response.statusText,
      errorData: errorData,
      message: errorData.message,
      error: errorData.error,
      details: errorData.details
    });
    throw new Error(errorData.message || `API error: ${response.status}`);
  }

  const data = await response.json();
  console.log('Gemini API response received:', {
    type,
    analysisLength: data.analysis?.length,
    timestamp: data.timestamp
  });

  if (!data.analysis) {
    console.error('❌ No analysis in response from backend:', data);
    throw new Error('No analysis generated by Gemini');
  }

  return data.analysis;
}

// =============================================================================
// SCORE EXPLANATION
// =============================================================================

/**
 * Generates an LLM explanation of team chemistry scores
 * Analyzes weekly score compared to season average
 *
 * @param {number} weeklyScore - Current week's team chemistry score
 * @param {number} overallAverage - Overall average score across all weeks
 * @param {object|null} gameInfo - Game/practice information (result, scores, performance rating)
 * @returns {Promise<string>} Natural language explanation of the scores
 */
export async function generateScoreExplanation(weeklyScore, overallAverage, gameInfo = null) {
  try {
    const prompt = buildScoreExplanationPrompt(weeklyScore, overallAverage, gameInfo);
    const explanation = await callGeminiAPI(prompt, 'score-explanation');
    return explanation;
  } catch (error) {
    console.error('Error generating score explanation:', error);
    return null;
  }
}

/**
 * Builds the prompt for score explanation analysis
 * @private
 */
function buildScoreExplanationPrompt(weeklyScore, overallAverage, gameInfo = null) {
  // Build game info section if available
  let gameInfoSection = '';
  if (gameInfo && !gameInfo.skipped) {
    const scoreInfo = gameInfo.result === 'No Game'
      ? '- No competitive game this week'
      : `- Score: ${gameInfo.yourScore} - ${gameInfo.opponentScore}`;

    gameInfoSection = `
**Game/Practice Context:**
- Game Result: ${gameInfo.result}
${scoreInfo}
- Practice Performance Rating: ${gameInfo.practicePerformance}/10
`;
  }

  return `You are an expert sports psychologist. Provide a brief 2-sentence analysis.

**Data:**
- Weekly Score: ${weeklyScore.toFixed(2)}
- Season Average: ${overallAverage.toFixed(2)}${gameInfoSection}

**Task:**
Write exactly 2 concise sentences:
1. Diagnose the team's cohesion level and key psychological factor (e.g., role clarity, trust, collective efficacy)${gameInfo && !gameInfo.skipped ? ', considering the game result and practice performance' : ''}
2. Compare to season average and state what this trend indicates

Be direct and specific. No JSON formatting.`;
}

// =============================================================================
// THINGS TO LOOK OUT FOR
// =============================================================================

/**
 * Generates an LLM analysis of team sentiment from open-ended quiz responses
 * Analyzes Q1 ("How do you feel the week went?") and Q9 ("Additional comments")
 *
 * @param {Array} playerResponses - Array of player response objects from the data array
 * @returns {Promise<string>} Natural language summary with player quotes
 */
export async function generateThingsToLookOutFor(playerResponses) {
  try {
    console.log('🔍 generateThingsToLookOutFor called with', playerResponses.length, 'player responses');
    const prompt = buildThingsToLookOutForPrompt(playerResponses);
    console.log('🔍 Prompt length:', prompt.length, 'characters');
    console.log('🔍 Calling Gemini API for team-insights...');
    const analysis = await callGeminiAPI(prompt, 'team-insights');
    console.log('🔍 Analysis received, length:', analysis?.length || 0);
    if (!analysis) {
      console.error('❌ generateThingsToLookOutFor: Analysis is null or empty!');
      return null;
    }
    return analysis;
  } catch (error) {
    console.error('❌ Error generating things to look out for:', error);
    console.error('❌ Error stack:', error.stack);
    return null;
  }
}

/**
 * Builds the prompt for analyzing open-ended player responses
 * @private
 */
function buildThingsToLookOutForPrompt(playerResponses) {
  // Filter and collect non-blank responses for Q1 and Q9
  const q1Responses = [];
  const q9Responses = [];

  playerResponses.forEach((player, index) => {
    const playerLabel = player.name || `Player ${index + 1}`;

    if (player.question1Answer && player.question1Answer.trim() !== '') {
      q1Responses.push(`${playerLabel}: "${player.question1Answer}"`);
    }

    if (player.question7Answer && player.question7Answer.trim() !== '') {
      q9Responses.push(`${playerLabel}: "${player.question7Answer}"`);
    }
  });

  // Build the responses section
  let responsesSection = '';

  if (q1Responses.length > 0) {
    responsesSection += `**Question 1: "How do you feel the week went?"**\n${q1Responses.join('\n')}\n\n`;
  }

  if (q9Responses.length > 0) {
    responsesSection += `**Question 9: "Additional comments"**\n${q9Responses.join('\n')}`;
  }

  // If no responses at all, return a message
  if (q1Responses.length === 0 && q9Responses.length === 0) {
    responsesSection = 'No open-ended responses provided this week.';
  }

  return `You are an expert sports psychologist analyzing team sentiment from player feedback.

**Player Responses:**
${responsesSection}

**Task:**
Provide a brief analysis in TWO sections:

1. **Team Sentiment Overview:** - Aggregate how the team is feeling about the week. Include specific player quotes using " " marks as evidence.

2. **Additional Notes** - Summarize any additional comments or concerns. Include specific player quotes using " " marks.

**Rules:**
- Your commentary (excluding quotes) must be MAX 50 words total across both sections
- Always include actual player quotes with " " marks to support your analysis
- Be concise and direct
- If a section has no responses, write "No responses provided."
- No JSON formatting

Format your response exactly like this:

**Team Sentiment Overview:**
[Your brief analysis with quotes]

**Additional Notes:**
[Your brief analysis with quotes]`;
}

