/**
 * Team Chemistry Dashboard - CONFIDENTIAL
 *
 * Displays team-level analytics ONLY (no individual player data)
 * Focus on aggregate metrics with 95% confidence intervals
 *
 */

import React from 'react';
import { useRealtimeData } from '../hooks/useRealtimeData';
import {
  calculateAverageScore,
  calculateTeamAverage,
  calculateTrend,
  getScoreColor,
  calculateDimensionAverages
} from '../utils/calculations';
import { generateScoreExplanation, analyzeTeamInsights } from '../services/geminiService';
import { BASELINE_SCORES } from '../config/constants';
import InsightsPanel from './InsightsPanel';
import TrendChart from './TrendChart';

const Dashboard = () => {
  const { data, loading, error, lastUpdated, refresh, scoreHistory, dimensionHistory, baselineData, hasBaseline } = useRealtimeData();

  // Calculate team-level metrics
  const teamAverage = calculateTeamAverage(data);
  const playerCount = data.length;

  const previousTeamAverage =
    scoreHistory.length >= 2 ? scoreHistory[scoreHistory.length - 2].score : null;

  const teamColor = getScoreColor(teamAverage);

  const dimensionAverages = React.useMemo(() => calculateDimensionAverages(data), [data]);

  const dimensionsWithTrends = React.useMemo(() => {
    // Get previous dimension data from history (if available)
    const previousDimensions = dimensionHistory.length >= 2
      ? dimensionHistory[dimensionHistory.length - 2].dimensions
      : null;

    return dimensionAverages.map((dimension, index) => {
      const previousAverage = previousDimensions?.[index]?.average ?? null;
      const currentAverage = dimension.average;

      // Calculate numeric difference from previous refresh
      const numericChange = previousAverage !== null
        ? currentAverage - previousAverage
        : null;

      return {
        ...dimension,
        trend: calculateTrend(currentAverage, previousAverage),
        previousAverage,
        numericChange
      };
    });
  }, [dimensionAverages, dimensionHistory]);

  // State for AI-generated content
  const [insights, setInsights] = React.useState({ summary: '', suggestions: [] });
  const [scoreExplanation, setScoreExplanation] = React.useState(null);
  const [insightsLoading, setInsightsLoading] = React.useState(false);
  const [explanationLoading, setExplanationLoading] = React.useState(false);
  const [initialAILoading, setInitialAILoading] = React.useState(false);

  // Calculate baseline average for score explanation
  // Use database baseline if available, otherwise use hardcoded values
  const baselineAverage = React.useMemo(() => {
    if (hasBaseline && baselineData) {
      const baselineValues = Object.values(baselineData);
      return baselineValues.reduce((sum, val) => sum + val, 0) / baselineValues.length;
    }
    return null; // No baseline available
  }, [hasBaseline, baselineData]);

  // Calculate overall average from score history
  const overallAverage = React.useMemo(() => {
    if (scoreHistory.length === 0) return teamAverage;
    const sum = scoreHistory.reduce((acc, entry) => acc + entry.score, 0);
    return sum / scoreHistory.length;
  }, [scoreHistory, teamAverage]);

  // Manual refresh function for score explanation (Call 1)
  const refreshScoreExplanation = async () => {
    if (data.length > 0) {
      setExplanationLoading(true);
      try {
        // Calculate difference if baseline exists
        const difference = hasBaseline ? teamAverage - baselineAverage : null;

        const explanation = await generateScoreExplanation(
          teamAverage,
          baselineAverage, // Will be null if no baseline
          difference,      // Will be null if no baseline
          overallAverage
        );
        setScoreExplanation(explanation);
      } catch (error) {
        console.error('Failed to generate score explanation:', error);
        setScoreExplanation('Unable to generate explanation. Please try again.');
      } finally {
        setExplanationLoading(false);
      }
    }
  };

  // Manual refresh function for AI insights (Call 2)
  const refreshInsights = async () => {
    if (data.length > 0) {
      setInsightsLoading(true);
      try {
        const aiInsights = await analyzeTeamInsights(data, teamAverage);
        setInsights(aiInsights); // Now returns { summary: '', suggestions: [] }
      } catch (error) {
        console.error('Failed to generate insights:', error);
        setInsights({ summary: '', suggestions: [] }); // Reset to empty structure
      } finally {
        setInsightsLoading(false);
      }
    }
  };

  // Auto-generate both score explanation and insights when data first loads
  const hasAutoGenerated = React.useRef(false);

  React.useEffect(() => {
    // Only auto-generate once when:
    // 1. Loading is complete (!loading)
    // 2. Data exists (data.length > 0)
    // 3. Haven't auto-generated yet (!hasAutoGenerated.current)
    if (!loading && data.length > 0 && !hasAutoGenerated.current) {
      hasAutoGenerated.current = true;

      // Add a small delay to ensure all data is fully loaded and stable
      const timer = setTimeout(async () => {
        console.log('Auto-generating AI analysis with', data.length, 'players');
        setInitialAILoading(true);

        try {
          // Generate both in parallel
          const promises = [];

          // Always generate score explanation
          promises.push(refreshScoreExplanation());

          // Only generate insights if there are text responses
          const hasTextResponses = data.some(player =>
            (player.question1Answer && player.question1Answer.trim()) ||
            (player.question7Answer && player.question7Answer.trim())
          );

          if (hasTextResponses) {
            promises.push(refreshInsights());
          }

          await Promise.all(promises);
          console.log('Auto-generation complete');
        } finally {
          setInitialAILoading(false);
        }
      }, 500);

      return () => clearTimeout(timer);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [loading, data.length]); // Only depend on loading and data.length to prevent double-firing

  /**
   * Empty State - No Data Loaded
   */
  if (data.length === 0 && !loading) {
    return (
      <div className="min-h-screen bg-white flex items-center justify-center p-4">
        <div className="text-center">
          <h2 className="text-xl sm:text-2xl font-bold text-gray-900 mb-3 sm:mb-4">No Data Loaded</h2>
          <p className="text-sm sm:text-base text-gray-600 mb-4 sm:mb-6">Click the refresh button to load team chemistry data</p>
          <button
            onClick={refresh}
            className="px-6 py-3 bg-blue-600 text-white rounded-lg font-semibold hover:bg-blue-700 transition-colors shadow-md min-h-[44px]"
          >
            Load Data
          </button>
        </div>
      </div>
    );
  }

  /**
   * Loading State
   */
  if (loading && data.length === 0) {
    return (
      <div className="min-h-screen bg-white flex items-center justify-center p-4">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 sm:h-16 sm:w-16 border-b-4 border-blue-600 mx-auto mb-4"></div>
          <p className="text-base sm:text-xl text-gray-700 font-semibold">Loading team analytics...</p>
        </div>
      </div>
    );
  }

  /**
   * Error State
   */
  if (error && data.length === 0) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center p-4">
        <div className="bg-white rounded-lg shadow-xl p-6 sm:p-8 max-w-md w-full">
          <div className="text-red-600 text-4xl sm:text-5xl mb-3 sm:mb-4">⚠</div>
          <h2 className="text-xl sm:text-2xl font-bold text-gray-800 mb-2">Error Loading Data</h2>
          <p className="text-sm sm:text-base text-gray-600 mb-4">{error}</p>
          <button
            onClick={refresh}
            className="bg-blue-600 text-white px-6 py-2.5 rounded-lg hover:bg-blue-700 transition-colors font-semibold min-h-[44px]"
          >
            Retry
          </button>
        </div>
      </div>
    );
  }

  // Helper function to get tier info with matching score colors
  const getTierInfo = (score) => {
    if (score >= 80) return { label: 'ELITE', range: '80-100', color: '#10b981' }; // Bright Green
    if (score >= 70) return { label: 'ABOVE AVERAGE', range: '70-79', color: '#059669' }; // Dark Green
    if (score >= 60) return { label: 'AVERAGE', range: '60-69', color: '#f59e0b' }; // Orange
    return { label: 'BELOW AVERAGE', range: '0-59', color: '#ef4444' }; // Red
  };

  const currentTier = getTierInfo(teamAverage);
  const currentDate = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  return (
    <div className="min-h-screen bg-white">
      {/* Professional Header */}
      <header className="py-4 sm:py-6" style={{ backgroundColor: 'rgb(50, 52, 52)' }}>
        <div className="w-full max-w-6xl mx-auto px-4 sm:px-8 lg:px-12">
          {/* Top row: Logo, Title, and Refresh button */}
          <div className="flex flex-col sm:flex-row sm:justify-between sm:items-start gap-4 mb-4">
            {/* Logo and Title */}
            <div className="flex items-center gap-3 sm:gap-4">
              <img src="/Ntangible.png" alt="Ntangible Logo" className="h-10 w-10 sm:h-12 sm:w-12 brightness-0 invert flex-shrink-0" />
              <div>
                <h1 className="text-xl sm:text-2xl lg:text-3xl font-bold text-white tracking-tight">TEAM CHEMISTRY REPORT</h1>
              </div>
            </div>

            {/* Date and Refresh button */}
            <div className="flex flex-col sm:flex-row items-start sm:items-center gap-3 sm:gap-6">
              <div className="text-left sm:text-right">
                <div className="text-xs sm:text-sm text-gray-400 uppercase tracking-wider">Report Date</div>
                <div className="text-base sm:text-lg font-semibold text-white">{currentDate}</div>
              </div>
              <button
                onClick={refresh}
                disabled={loading}
                className={`px-4 py-2.5 rounded-lg font-semibold transition-all shadow-md min-h-[44px] ${
                  loading
                    ? 'bg-gray-600 text-gray-400 cursor-not-allowed'
                    : 'bg-white text-gray-800 hover:bg-gray-100 active:scale-95'
                }`}
              >
                {loading ? (
                  <>
                    <span className="inline-block animate-spin mr-2">⟳</span>
                    Loading...
                  </>
                ) : (
                  <>
                    <span className="mr-2">⟳</span>
                    Refresh Data
                  </>
                )}
              </button>
            </div>
          </div>

          {/* Report Details */}
          <div className="flex flex-col sm:flex-row gap-3 sm:gap-8 text-xs sm:text-sm">
            <div>
              <span className="text-gray-400 uppercase tracking-wider">Number of Players: </span>
              <span className="font-semibold text-white">{playerCount}</span>
            </div>
            <div>
              <span className="text-gray-400 uppercase tracking-wider">Last Updated: </span>
              <span className="font-semibold text-white">
                {lastUpdated ? new Date(lastUpdated).toLocaleTimeString() : 'Never'}
              </span>
            </div>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="w-full max-w-6xl mx-auto px-4 sm:px-8 lg:px-12 py-12">

        {/* Hero Section - Score and Trend Chart */}
        <div className="flex flex-col lg:grid lg:grid-cols-[1fr,auto] gap-6 lg:gap-8 mb-12 pb-8 border-b-2 border-gray-200">
          {/* Main Score */}
          <div>
            <h2 className="text-xs sm:text-sm font-semibold text-gray-600 uppercase tracking-wider mb-2">
              NGAUGE TEAM CHEMISTRY SCORE
            </h2>
            <div className="flex items-baseline gap-3 sm:gap-6 mb-4 sm:mb-6">
              <div className="text-5xl sm:text-6xl lg:text-8xl font-black tracking-tight" style={{ color: teamColor }}>
                {teamAverage.toFixed(1)}
              </div>
              {(() => {
                const trend = previousTeamAverage !== null
                  ? calculateTrend(teamAverage, previousTeamAverage)
                  : { direction: 'stable', color: '#6b7280' };

                return (
                  <div className="text-3xl sm:text-4xl lg:text-5xl font-bold" style={{ color: trend.color }}>
                    {trend.direction === 'up' ? '↑' : trend.direction === 'down' ? '↓' : '→'}
                  </div>
                );
              })()}
            </div>

            {/* Current Tier Badge */}
            <div
              className="inline-block px-4 py-2 sm:px-6 sm:py-3 rounded-lg border-2 bg-white"
              style={{ borderColor: currentTier.color }}
            >
              <div className="text-base sm:text-lg font-bold tracking-wide text-gray-900">{currentTier.label}</div>
            </div>
          </div>

          {/* Trend Chart */}
          <div className="flex items-center justify-center lg:justify-start">
            <TrendChart scoreHistory={scoreHistory} currentScore={teamAverage} />
          </div>
        </div>

        {/* What do NGauge scores mean - Two Column Layout */}
        <div className="flex flex-col lg:grid lg:grid-cols-[2fr,1fr] gap-6 lg:gap-12 mb-12 pb-12 border-b-2 border-gray-200">
          {/* Left: Explanation */}
          <div>
            <h2 className="text-xl sm:text-2xl font-bold text-gray-900 mb-3 sm:mb-4 uppercase tracking-tight">
              What do NGauge scores mean?
            </h2>
            <p className="text-sm sm:text-base text-gray-700 leading-relaxed">
              NGauge scores accurately measure team chemistry on a 100-point scale, reflecting how <strong>connected, clear, and ready</strong> the team feels. These scores use your teams baseline chemistry score to denoise
              the data and show you the most <strong>meaningful changes in team chemistry.</strong>
            </p>
          </div>

          {/* Right: Score Classification Bars */}
          <div className="flex flex-col justify-center space-y-2 sm:space-y-3">
            <div className="rounded-lg px-3 py-2 border-2 bg-white" style={{ borderColor: '#10b981' }}>
              <div className="flex justify-between items-center text-xs sm:text-sm">
                <span className="font-bold tracking-wide text-gray-900">ELITE</span>
                <span className="font-semibold text-gray-700">80+</span>
              </div>
            </div>

            <div className="rounded-lg px-3 py-2 border-2 bg-white" style={{ borderColor: '#059669' }}>
              <div className="flex justify-between items-center text-xs sm:text-sm">
                <span className="font-bold tracking-wide text-gray-900">ABOVE AVERAGE</span>
                <span className="font-semibold text-gray-700">70-79</span>
              </div>
            </div>

            <div className="rounded-lg px-3 py-2 border-2 bg-white" style={{ borderColor: '#f59e0b' }}>
              <div className="flex justify-between items-center text-xs sm:text-sm">
                <span className="font-bold tracking-wide text-gray-900">AVERAGE</span>
                <span className="font-semibold text-gray-700">60-69</span>
              </div>
            </div>

            <div className="rounded-lg px-3 py-2 border-2 bg-white" style={{ borderColor: '#ef4444' }}>
              <div className="flex justify-between items-center text-xs sm:text-sm">
                <span className="font-bold tracking-wide text-gray-900">BELOW AVERAGE</span>
                <span className="font-semibold text-gray-700">0-59</span>
              </div>
            </div>
          </div>
        </div>

        {/* Findings */}
        <div className="mb-12 pb-12 border-b-2 border-gray-200">
          <div className="mb-3 flex flex-wrap items-center justify-between gap-3 sm:gap-4">
            <h2 className="text-xl sm:text-2xl font-bold text-gray-900 uppercase tracking-tight">FINDINGS</h2>
            <button
              onClick={refreshScoreExplanation}
              disabled={explanationLoading}
              className={`px-4 sm:px-5 py-2.5 rounded-lg font-semibold transition-all shadow-md min-h-[44px] text-sm sm:text-base ${
                explanationLoading
                  ? 'bg-gray-300 text-gray-500 cursor-not-allowed'
                  : 'bg-green-600 text-white hover:bg-green-700 active:scale-95 hover:shadow-lg'
              }`}
            >
              {explanationLoading ? (
                <>
                  <span className="inline-block animate-spin mr-2">⟳</span>
                  Analyzing...
                </>
              ) : (
                'Explain Scores'
              )}
            </button>
          </div>

          {/* Column Headers - Hidden on mobile, shown on md+ */}
          <div className="hidden md:grid grid-cols-1 md:grid-cols-2 gap-3 mb-2">
            <div className={`grid ${hasBaseline ? 'grid-cols-[1fr,auto,auto]' : 'grid-cols-[1fr,auto]'} gap-3 sm:gap-6 px-3 items-center`}>
              <div className="text-xs font-bold text-gray-600 uppercase tracking-wider">Dimension</div>
              <div className="text-xs font-bold text-gray-600 uppercase tracking-wider text-right" style={{ minWidth: '80px' }}>Weekly</div>
              {hasBaseline && (
                <div className="text-xs font-bold text-gray-600 uppercase tracking-wider text-right" style={{ minWidth: '60px' }}>Baseline</div>
              )}
            </div>
            <div className={`grid ${hasBaseline ? 'grid-cols-[1fr,auto,auto]' : 'grid-cols-[1fr,auto]'} gap-3 sm:gap-6 px-3 items-center`}>
              <div className="text-xs font-bold text-gray-600 uppercase tracking-wider">Dimension</div>
              <div className="text-xs font-bold text-gray-600 uppercase tracking-wider text-right" style={{ minWidth: '80px' }}>Weekly</div>
              {hasBaseline && (
                <div className="text-xs font-bold text-gray-600 uppercase tracking-wider text-right" style={{ minWidth: '60px' }}>Baseline</div>
              )}
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            {dimensionsWithTrends.map((dimension, index) => {
              const dimColor = getScoreColor(dimension.average);
              const weeklyScore = dimension.average;

              // Get baseline score from database if available
              const baselineScore = hasBaseline && baselineData
                ? baselineData[dimension.name] || 0
                : null;

              // Calculate difference only if baseline exists
              const difference = baselineScore !== null ? weeklyScore - baselineScore : null;

              // ALWAYS show weekly trend (comparison to last refresh)
              // Baseline column is separate and shows baseline value when available
              let diffDisplay, diffColor, diffArrow;

              if (dimension.trend && dimension.numericChange !== null) {
                // Show numeric change and arrow
                const change = dimension.numericChange;
                const absChange = Math.abs(change);

                if (absChange < 0.5) {
                  // Negligible change
                  diffDisplay = '--';
                  diffColor = '#6b7280';
                  diffArrow = '';
                } else {
                  // Significant change - show number + arrow
                  diffDisplay = `${change > 0 ? '+' : ''}${change.toFixed(1)}`;
                  diffColor = dimension.trend.color;
                  diffArrow = dimension.trend.direction === 'up' ? '↑'
                    : dimension.trend.direction === 'down' ? '↓'
                    : '';
                }
              } else {
                // No trend data yet (first load)
                diffDisplay = null;
                diffColor = null;
                diffArrow = null;
              }

              return (
                <div
                  key={index}
                  className="bg-white border-l-4 rounded px-3 py-2.5 h-full"
                  style={{ borderLeftColor: dimColor }}
                >
                  <div className={`grid ${hasBaseline ? 'grid-cols-[1fr,auto,auto]' : 'grid-cols-[1fr,auto]'} gap-3 sm:gap-6 items-center`}>
                    {/* Dimension Name */}
                    <div className="font-semibold text-gray-900 text-xs sm:text-sm">
                      {dimension.name}
                    </div>

                    {/* Weekly Score + Weekly Trend */}
                    <div className="flex items-baseline gap-1 sm:gap-2 justify-end" style={{ minWidth: '70px' }}>
                      <span className="text-base sm:text-lg font-bold" style={{ color: dimColor }}>
                        {weeklyScore.toFixed(1)}
                      </span>
                      {/* Show weekly trend (comparison to last refresh) */}
                      {diffDisplay !== null && diffArrow !== null && (
                        <span
                          className="text-xs sm:text-sm font-semibold"
                          style={{ color: diffColor }}
                        >
                          {diffDisplay}{diffArrow}
                        </span>
                      )}
                    </div>

                    {/* Baseline Score - Only show if baseline exists */}
                    {hasBaseline && baselineScore !== null && (
                      <div className="text-right" style={{ minWidth: '50px' }}>
                        <span className="text-base sm:text-lg font-bold text-gray-500">
                          {baselineScore.toFixed(1)}
                        </span>
                      </div>
                    )}
                  </div>
                </div>
              );
            })}
          </div>

          {/* LLM Score Explanation Section */}
          <div className="mt-6">
            <h3 className="text-base sm:text-lg font-bold text-gray-900 mb-3 uppercase tracking-tight">
              Score Analysis
            </h3>
            {scoreExplanation ? (
              <div className="text-sm sm:text-base text-gray-900 leading-relaxed whitespace-pre-line">
                {scoreExplanation}
              </div>
            ) : (
              <p className="text-sm sm:text-base text-gray-900">
                {hasBaseline
                  ? "Click \"Explain Scores\" to generate an AI-powered analysis of the variance between baseline and weekly scores, and how this trend could impact your overall team chemistry average."
                  : "Click \"Explain Scores\" to generate an AI-powered analysis of your weekly scores and overall team chemistry trends. (Note: No baseline data available for comparison)"}
              </p>
            )}
          </div>
        </div>

        {/* AI INSIGHTS PANEL */}
        <div className="mb-12">
          <div className="mb-3 flex flex-wrap items-center justify-between gap-3 sm:gap-4">
            <h2 className="text-xl sm:text-2xl font-bold text-gray-900 uppercase tracking-tight">THINGS TO LOOK OUT FOR</h2>
            <button
              onClick={refreshInsights}
              disabled={insightsLoading}
              className={`px-4 sm:px-5 py-2.5 rounded-lg font-semibold transition-all shadow-md min-h-[44px] text-sm sm:text-base ${
                insightsLoading
                  ? 'bg-gray-300 text-gray-500 cursor-not-allowed'
                  : 'bg-blue-600 text-white hover:bg-blue-700 active:scale-95 hover:shadow-lg'
              }`}
            >
              {insightsLoading ? (
                <>
                  <span className="inline-block animate-spin mr-2">⟳</span>
                  Analyzing...
                </>
              ) : (
                'Generate Insights'
              )}
            </button>
          </div>

          {/* Player Notes Summary - styled like Score Analysis */}
          {insights.summary && (
            <div className="mb-6">
              <h3 className="text-base sm:text-lg font-bold text-gray-900 mb-3 uppercase tracking-tight">
                Player Notes Summary
              </h3>
              <div className="text-sm sm:text-base text-gray-900 leading-relaxed whitespace-pre-line">
                {insights.summary}
              </div>
            </div>
          )}

          <InsightsPanel suggestions={insights.suggestions} />
        </div>

      </main>

      {/* Footer */}
      <footer className="border-t-2 border-gray-200 py-4 sm:py-6 bg-gray-50">
        <div className="w-full max-w-6xl mx-auto px-4 sm:px-8 lg:px-12 text-center">
          <p className="text-xs sm:text-sm text-gray-600 font-medium">
            NGauge Team Chemistry Report - Confidential
          </p>
          <p className="text-xs text-gray-500 mt-1">
            Generated by NTangible Analytics Platform
          </p>
        </div>
      </footer>

      {/* Initial AI Loading Overlay */}
      {initialAILoading && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-white rounded-lg shadow-xl p-8 max-w-md mx-4">
            <div className="text-center">
              <div className="animate-spin rounded-full h-16 w-16 border-b-4 border-blue-600 mx-auto mb-4"></div>
              <h3 className="text-xl font-bold text-gray-900 mb-2">Generating AI Analysis</h3>
              <p className="text-gray-600">
                Please wait while we analyze your team data and generate insights...
              </p>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default Dashboard;
