/**
 * Vercel Serverless Function: /api/analyze
 *
 * Analyzes team data using Google Gemini AI
 * Supports score explanations and team insights
 *
 * SECURITY:
 * - Input validation and sanitization
 * - Request timeout protection
 * - Prompt length limits
 * - API key stored securely in Vercel
 */

// API timeout
const API_TIMEOUT = 30000;

/**
 * Configuration for different analysis types
 */
const ANALYSIS_CONFIGS = {
  'score-explanation': {
    model: 'gemini-2.5-flash',
    temperature: 0.5,
    maxOutputTokens: 1800,  // Increased for 3-4 sentence diagnostic depth
  },
  'team-insights': {
    model: 'gemini-2.5-flash',
    temperature: 0.6,  // Balanced for diagnostic focus with evidence-based insights
    maxOutputTokens: 2048,
  }
};

/**
 * Fetch with timeout support
 */
async function fetchWithTimeout(url, options = {}, timeout = API_TIMEOUT) {
  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), timeout);

  try {
    const response = await fetch(url, {
      ...options,
      signal: controller.signal
    });
    clearTimeout(timeoutId);
    return response;
  } catch (error) {
    clearTimeout(timeoutId);
    if (error.name === 'AbortError') {
      throw new Error('Request timeout - external service took too long to respond');
    }
    throw error;
  }
}

/**
 * Validate request body
 */
function validateRequest(body) {
  const errors = [];

  if (!body.prompt) {
    errors.push('Prompt is required');
  } else if (typeof body.prompt !== 'string') {
    errors.push('Prompt must be a string');
  } else if (body.prompt.length < 10) {
    errors.push('Prompt must be at least 10 characters');
  } else if (body.prompt.length > 50000) {
    errors.push('Prompt must be less than 50,000 characters');
  }

  if (body.type && !['team-insights', 'score-explanation'].includes(body.type)) {
    errors.push('Invalid analysis type. Must be "team-insights" or "score-explanation"');
  }

  return errors;
}

/**
 * Main handler function
 */
export default async function handler(req, res) {
  // Only allow POST requests
  if (req.method !== 'POST') {
    return res.status(405).json({
      success: false,
      error: 'Method not allowed',
      message: 'Only POST requests are accepted'
    });
  }

  try {
    const GEMINI_API_KEY = process.env.GEMINI_API_KEY;

    if (!GEMINI_API_KEY) {
      throw new Error('GEMINI_API_KEY environment variable not set');
    }

    // Validate request body
    const validationErrors = validateRequest(req.body);
    if (validationErrors.length > 0) {
      return res.status(400).json({
        success: false,
        error: 'Validation failed',
        details: validationErrors
      });
    }

    const { prompt, type = 'team-insights', config } = req.body;

    // Get configuration for analysis type
    const analysisConfig = config || ANALYSIS_CONFIGS[type] || ANALYSIS_CONFIGS['team-insights'];

    console.log(`📊 Running ${type} analysis with config:`, {
      model: analysisConfig.model,
      temperature: analysisConfig.temperature,
      maxTokens: analysisConfig.maxOutputTokens
    });

    // Call Gemini API with timeout
    const geminiUrl = `https://generativelanguage.googleapis.com/v1beta/models/${analysisConfig.model}:generateContent?key=${GEMINI_API_KEY}`;

    const geminiResponse = await fetchWithTimeout(geminiUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [{
          parts: [{
            text: prompt
          }]
        }],
        generationConfig: {
          temperature: analysisConfig.temperature,
          maxOutputTokens: analysisConfig.maxOutputTokens,
          responseMimeType: type === 'team-insights' ? 'application/json' : undefined,
        }
      })
    });

    if (!geminiResponse.ok) {
      const errorData = await geminiResponse.json().catch(() => ({}));
      throw new Error(errorData.error?.message || `Gemini API error: ${geminiResponse.status}`);
    }

    const geminiData = await geminiResponse.json();

    // Extract the generated text
    const analysis = geminiData.candidates?.[0]?.content?.parts?.[0]?.text || '';

    if (!analysis) {
      throw new Error('No analysis generated by Gemini');
    }

    return res.status(200).json({
      success: true,
      analysis,
      type,
      timestamp: new Date().toISOString()
    });

  } catch (error) {
    console.error('Error calling Gemini API:', error);

    return res.status(500).json({
      success: false,
      error: 'Failed to generate analysis',
      message: process.env.NODE_ENV === 'development'
        ? error.message
        : 'Unable to process your request at this time'
    });
  }
}
