/**
 * Vercel Serverless Function: /api/analyze
 *
 * Analyzes team data using Claude AI
 * Supports score explanations and team insights
 *
 * SECURITY:
 * - Input validation and sanitization
 * - Request timeout protection
 * - Prompt length limits
 * - API key stored securely in Vercel
 */

// API timeout
const API_TIMEOUT = 30000;

/**
 * Configuration for different analysis types
 */
const ANALYSIS_CONFIGS = {
  'score-explanation': {
    model: 'claude-3-haiku-20240307',
    temperature: 0.5,
    maxTokens: 1800,  // Increased for 3-4 sentence diagnostic depth
  },
  'team-insights': {
    model: 'claude-3-haiku-20240307',
    temperature: 0.6,
    maxTokens: 2048,  // Increased for concise insights
  }
};

/**
 * Fetch with timeout support
 */
async function fetchWithTimeout(url, options = {}, timeout = API_TIMEOUT) {
  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), timeout);

  try {
    const response = await fetch(url, {
      ...options,
      signal: controller.signal
    });
    clearTimeout(timeoutId);
    return response;
  } catch (error) {
    clearTimeout(timeoutId);
    if (error.name === 'AbortError') {
      throw new Error('Request timeout - external service took too long to respond');
    }
    throw error;
  }
}

/**
 * Validate request body
 */
function validateRequest(body) {
  const errors = [];

  if (!body.prompt) {
    errors.push('Prompt is required');
  } else if (typeof body.prompt !== 'string') {
    errors.push('Prompt must be a string');
  } else if (body.prompt.length < 10) {
    errors.push('Prompt must be at least 10 characters');
  } else if (body.prompt.length > 50000) {
    errors.push('Prompt must be less than 50,000 characters');
  }

  if (body.type && !['team-insights', 'score-explanation'].includes(body.type)) {
    errors.push('Invalid analysis type. Must be "team-insights" or "score-explanation"');
  }

  return errors;
}

/**
 * Main handler function
 */
export default async function handler(req, res) {
  // Only allow POST requests
  if (req.method !== 'POST') {
    return res.status(405).json({
      success: false,
      error: 'Method not allowed',
      message: 'Only POST requests are accepted'
    });
  }

  try {
    const CLAUDE_API_KEY = process.env.CLAUDE_API_KEY;

    if (!CLAUDE_API_KEY) {
      throw new Error('CLAUDE_API_KEY environment variable not set');
    }

    // Validate request body
    const validationErrors = validateRequest(req.body);
    if (validationErrors.length > 0) {
      return res.status(400).json({
        success: false,
        error: 'Validation failed',
        details: validationErrors
      });
    }

    const { prompt, type = 'team-insights', config } = req.body;

    // Get configuration for analysis type
    const analysisConfig = config || ANALYSIS_CONFIGS[type] || ANALYSIS_CONFIGS['team-insights'];

    console.log(`📊 Running ${type} analysis with config:`, {
      model: analysisConfig.model,
      temperature: analysisConfig.temperature,
      maxTokens: analysisConfig.maxOutputTokens
    });

    // Call Claude API with timeout
    const claudeUrl = 'https://api.anthropic.com/v1/messages';

    const claudeResponse = await fetchWithTimeout(claudeUrl, {
      method: 'POST',
      headers: {
        'x-api-key': CLAUDE_API_KEY,
        'anthropic-version': '2023-06-01',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: analysisConfig.model,
        max_tokens: analysisConfig.maxTokens,
        temperature: analysisConfig.temperature,
        messages: [{
          role: 'user',
          content: prompt
        }]
      })
    });

    if (!claudeResponse.ok) {
      const errorData = await claudeResponse.json().catch(() => ({}));
      console.error('Claude API error:', errorData);
      throw new Error(errorData.error?.message || `Claude API error: ${claudeResponse.status}`);
    }

    const claudeData = await claudeResponse.json();
    console.log('Claude response metadata:', {
      stopReason: claudeData.stop_reason,
      inputTokens: claudeData.usage?.input_tokens,
      outputTokens: claudeData.usage?.output_tokens
    });

    // Extract the generated text
    const analysis = claudeData.content?.[0]?.text || '';

    if (!analysis) {
      console.error('No analysis in response:', claudeData);
      throw new Error('No analysis generated by Claude');
    }

    console.log('Analysis extracted, length:', analysis.length, 'stopReason:', claudeData.stop_reason);



    return res.status(200).json({
      success: true,
      analysis,
      type,
      timestamp: new Date().toISOString()
    });

  } catch (error) {
    console.error('Error calling Claude API:', error);

    return res.status(500).json({
      success: false,
      error: 'Failed to generate analysis',
      message: process.env.NODE_ENV === 'development'
        ? error.message
        : 'Unable to process your request at this time'
    });
  }
}
